version: "3"
services:
  food-db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      POSTGRES_DB: ${FOOD_DB_NAME}
      POSTGRES_USER: ${FOOD_DB_USER}
      POSTGRES_PASSWORD: ${FOOD_DB_PASSWORD}
    volumes:
      - food-data:/var/lib/postgresql/data

  auth-db:
    image: postgres:16-alpine
    networks:
      - backend
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - auth-data:/var/lib/postgresql/data

  config:
    image: kine/config:latest
    networks:
      - backend
    env_file:
      - .env
    volumes:
      - "${SPRING_CONFIG_GIT_URI}:/config"

  discovery:
    image: kine/discovery:latest
    networks:
      - backend
    env_file:
      - .env

  gateway:
    image: kine/gateway:latest
    networks:
      - backend
    ports:
      - "3000:${GATEWAY_PORT}"
    env_file:
      - .env

  food-service:
    image: kine/food-service:latest
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - food-db

  calculator-service:
    image: kine/calculator-service:latest
    networks:
      - backend
    env_file:
      - .env

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - "8080:${KEYCLOAK_PORT}"
      - "8043:8443"
    networks:
      - backend
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME_URL: ${KC_FRONTEND_URL}
      KC_HOSTNAME_ADMIN_URL: ${KC_ADMIN_URL}
      KC_DB: postgres
      KC_DB_URL: ${AUTH_DB_URL}
      KC_DB_USERNAME: ${AUTH_DB_USER}
      KC_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      KC_HEALTH_ENABLED: true
      KC_PROXY_ADDRESS_FORWARDING: true
      KC_HOSTNAME_DEBUG: true
    depends_on:
      - auth-db

volumes:
  food-data:
  auth-data:

networks:
  backend:
    driver: bridge