version: "3"
services:
  food-db:
    image: postgres:16-alpine
    networks:
      - backend
    environment:
      POSTGRES_DB: ${FOOD_DB_NAME}
      POSTGRES_USER: ${FOOD_DB_USER}
      POSTGRES_PASSWORD: ${FOOD_DB_PASSWORD}
    volumes:
      - food-data:/var/lib/postgresql/data

  auth-db:
    image: postgres:16-alpine
    networks:
      - backend
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - auth-data:/var/lib/postgresql/data

  config:
    image: kine/config:latest
    networks:
      - backend
    ports:
      - "8081:${CONFIG_PORT}"
    env_file:
      - .env
    volumes:
      - "${SPRING_CONFIG_GIT_URI}:/config"

  discovery:
    image: kine/discovery:latest
    networks:
      - backend
    ports:
      - "8082:${DISCOVERY_PORT}"
    env_file:
      - .env
    depends_on:
      - config

  gateway:
    image: kine/gateway:latest
    networks:
      - backend
    ports:
      - "8080:${GATEWAY_PORT}"
    env_file:
      - .env
    depends_on:
      - discovery

  food-service:
    image: kine/food-service:latest
    ports:
      - "7084:${FOOD_SERVICE_PORT}"
    networks:
      - backend
    env_file:
      - .env
    depends_on:
      - discovery
      - food-db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    ports:
      - "7080:${KEYCLOAK_PORT}"
    networks:
      - backend
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTP_PORT: ${KEYCLOAK_PORT}
      KC_HTTP_RELATIVE_PATH: ${KC_HTTP_RELATIVE_PATH}
      KC_DB: postgres
      KC_DB_URL: ${AUTH_DB_URL}
      KC_DB_USERNAME: ${AUTH_DB_USER}
      KC_DB_PASSWORD: ${AUTH_DB_PASSWORD}
      KC_HEALTH_ENABLED: true
    depends_on:
      - auth-db

volumes:
  food-data:
  auth-data:

networks:
  backend:
    driver: bridge