apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculator-service
  template:
    metadata:
      labels:
        app: calculator-service
    spec:
      containers:
        - name: calculator-service
          image: kinefit/calculator-service:latest
          envFrom:
            - secretRef:
                name: kine-secrets
