apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-service
  template:
    metadata:
      labels:
        app: food-service
    spec:
      containers:
        - name: food-service
          image: kinefit/food-service:latest
          envFrom:
            - secretRef:
                name: kine-secrets
