apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
    - name: curl-container
      image: curlimages/curl
      command: ["sleep"]
      args: ["3600"]  # Keeps the pod alive for 1 hour
