apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  type: ClusterIP
  selector:
    app: calculator-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
