server:
  port: 8080

spring:
  application:
    name: ${CONFIG_SERVICE_ID}
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CONFIG_GIT_URI}
          default-label: master
          clone-on-start: true
  security:
    user:
      name: ${CONFIG_USER}
      password: ${CONFIG_PASSWORD}

eureka:
  instance:
    hostname: ${CONFIG_SERVICE_ID}
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL}
    region: default
    registry-fetch-interval-seconds: 30
