server:
  port: 8080

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/oussamaty/kine-config
  security:
    user:
      name: user
      password: password

eureka:
  client:
    service-url:
      defaultZone: http://discovery:8080/eureka/
    region: default
    registry-fetch-interval-seconds: 10